export function customData() {
    return [
        {
            "id": 1,
            "customerId": "8101445",
            "customerName": "季祥弟",
            "customerAge": 56,
            "customerTel": 17557282929,
            "customerTags": [
                "A级客户",
                "稳健型",
                "有信用卡",
                "有房无车",
                "高消费",
                "爱喝茶"
            ],
            "RecomProducts": [
                "汇利丰结构性理财",
                "个人汽车贷款"
            ],
            "customerType": 3,
            "followUpStatus": '跟进',
            "handeler": "戴晓军",
            "gender": "man",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050820@qq.com",
            "maritalStatus": 1,
            "educationStatus": 1,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 1,
            "personalLoan": 2,
            "credit": 1,
            "timeDeposit": 1,
            "isNew": false,
            "key": "1"
        },
        {
            "id": 2,
            "customerId": "8101466",
            "customerName": "赵友胜",
            "customerAge": 51,
            "customerTel": 13023625995,
            "customerTags": [
                "B级客户",
                "稳健型",
                "有房贷",
                "有理财",
                "高消费",
                "旅游达人"
            ],
            "RecomProducts": [
                "诗意生活信用卡"
            ],
            "customerType": 3,
            "followUpStatus": '跟进',
            "handeler": "李小引",
            "gender": "man",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050821@qq.com",
            "maritalStatus": 1,
            "educationStatus": 1,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 1,
            "personalLoan": 2,
            "credit": 1,
            "timeDeposit": 1,
            "isNew": true,
            "key": "2"
        },
        {
            "id": 3,
            "customerId": "8101579",
            "customerName": "吴永友",
            "customerAge": 43,
            "customerTel": 13295712112,
            "customerTags": [
                "A级客户",
                "保守型",
                "有信用卡",
                "有房有车",
                "高消费",
                "高收入",
                "爱喝茶"
            ],
            "RecomProducts": [
                "汇利丰结构性理财",
                "随薪贷"
            ],
            "customerType": 3,
            "followUpStatus": '跟进',
            "handeler": "潘成志",
            "gender": "man",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050822@qq.com",
            "maritalStatus": 1,
            "educationStatus": 1,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 1,
            "personalLoan": 2,
            "credit": 1,
            "timeDeposit": 1,
            "isNew": true,
            "key": "3"
        },
        {
            "id": 4,
            "customerId": "8101443",
            "customerName": "李荣媚",
            "customerAge": 46,
            "customerTel": 13093711661,
            "customerTags": [
                "A级客户",
                "稳健型",
                "有理财",
                "有房有车",
                "高收入",
                "喜欢运动"
            ],
            "RecomProducts": [
                "爱奇艺联名信用卡",
                "随薪贷"
            ],
            "customerType": 3,
            "followUpStatus": '跟进',
            "handeler": "戴丽曼",
            "gender": "woman",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050822@qq.com",
            "maritalStatus": 1,
            "educationStatus": 1,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 1,
            "personalLoan": 2,
            "credit": 1,
            "timeDeposit": 1,
            "isNew": true,
            "key": "4"
        },
        {
            "id": 5,
            "customerId": "8101459",
            "customerName": "杨选泽",
            "customerAge": 20,
            "customerTel": 13067951331,
            "customerTags": [
                "B级客户",
                "稳健型",
                "有信用卡",
                "无房无车",
                "高消费",
                "旅游达人"
            ],
            "RecomProducts": [
                "汇利丰结构性理财",
                "留学贷款"
            ],
            "customerType": 3,
            "followUpStatus": '跟进',
            "handeler": "林胜洁",
            "gender": "man",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050822@qq.com",
            "maritalStatus": 2,
            "educationStatus": 1,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 2,
            "personalLoan": 2,
            "credit": 1,
            "timeDeposit": 1,
            "isNew": true,
            "key": "5"
        },
        {
            "id": 6,
            "customerId": "8101464",
            "customerName": "任建弟",
            "customerAge": 51,
            "customerTel": 17681890765,
            "customerTags": [
                "A级客户",
                "保守型",
                "有信用卡",
                "有房有车",
                "高收入",
                "爱喝茶"
            ],
            "RecomProducts": [
                "汇利丰结构性理财",
                "随薪贷"
            ],
            "customerType": 3,
            "followUpStatus": '跟进',
            "handeler": "李克俊",
            "gender": "man",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050822@qq.com",
            "maritalStatus": 1,
            "educationStatus": 1,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 2,
            "personalLoan": 2,
            "credit": 1,
            "timeDeposit": 1,
            "isNew": true,
            "key": "6"
        },
        {
            "id": 7,
            "customerId": "8101464",
            "customerName": "丁丽盛",
            "customerAge": 50,
            "customerTel": 13216151112,
            "customerTags": [
                "A级客户",
                "稳健型",
                "有理财",
                "有房有车",
                "高消费",
                "爱喝茶"
            ],
            "RecomProducts": [
                "网易云音乐联名卡",
                "随薪贷"
            ],
            "customerType": 2,
            "followUpStatus": "跟进",
            "handeler": "陈志坚",
            "gender": "man",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050826@qq.com",
            "maritalStatus": 1,
            "educationStatus": 1,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 2,
            "personalLoan": 2,
            "credit": 1,
            "timeDeposit": 1,
            "isNew": true,
            "key": "7"
        },
        {
            "id": 8,
            "customerId": "8101469",
            "customerName": "王颖颖",
            "customerAge": 45,
            "customerTel": 17557282626,
            "customerTags": [
                "A级客户",
                "积极型",
                "有信用卡",
                "有理财",
                "有房有车",
                "高消费",
                "爱喝茶"
            ],
            "RecomProducts": [
                "爱奇艺联名信用卡",
                "随薪贷"
            ],
            "customerType": 2,
            "followUpStatus": "跟进",
            "handeler": "陈志坚",
            "gender": "woman",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050827@qq.com",
            "maritalStatus": 1,
            "educationStatus": 1,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 2,
            "personalLoan": 1,
            "credit": 1,
            "timeDeposit": 1,
            "isNew": true,
            "key": "8"
        },
        {
            "id": 9,
            "customerId": "8101586",
            "customerName": "陈龙辉",
            "customerAge": 46,
            "customerTel": 15669915321,
            "customerTags": [
                "C级客户",
                "稳健型",
                "有房贷",
                "有房无车",
                "高消费",
                "喜欢运动"
            ],
            "RecomProducts": [
                "汇利丰结构性理财",
                "个人汽车贷款"
            ],
            "customerType": 2,
            "followUpStatus": "待跟进",
            "handeler": "陈志坚",
            "gender": "man",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050828@qq.com",
            "maritalStatus": 1,
            "educationStatus": 1,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 2,
            "personalLoan": 1,
            "credit": 2,
            "timeDeposit": 2,
            "isNew": true,
            "key": "9"
        },
        {
            "id": 10,
            "customerId": "8101775",
            "customerName": "申屠升伟",
            "customerAge": 43,
            "customerTel": 13093710550,
            "customerTags": [
                "A级客户",
                "保守型",
                "有信用卡",
                "有房有车",
                "高消费",
                "爱喝茶"
            ],
            "RecomProducts": [
                "爱奇艺联名信用卡",
                "随薪贷"
            ],
            "customerType": 2,
            "followUpStatus": "待跟进",
            "handeler": "陈志坚",
            "gender": "man",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050829@qq.com",
            "maritalStatus": 1,
            "educationStatus": 2,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 2,
            "personalLoan": 1,
            "credit": 2,
            "timeDeposit": 2,
            "isNew": false,
            "key": "10"
        },
        {
            "id": 11,
            "customerId": "8103112",
            "customerName": "单素微",
            "customerAge": 50,
            "customerTel": 17606505151,
            "customerTags": [
                "A级客户",
                "稳健型",
                "有信用卡",
                "有房无车",
                "高消费",
                "旅游达人"
            ],
            "RecomProducts": [
                "汇利丰结构性理财",
                "个人汽车贷款"
            ],
            "customerType": 1,
            "followUpStatus": "待跟进",
            "handeler": "陈志坚",
            "gender": "woman",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050829@qq.com",
            "maritalStatus": 1,
            "educationStatus": 2,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 2,
            "personalLoan": 1,
            "credit": 2,
            "timeDeposit": 2,
            "isNew": true,
            "key": "11"
        },
        {
            "id": 12,
            "customerId": "8104178",
            "customerName": "林民",
            "customerAge": 54,
            "customerTel": 13123953223,
            "customerTags": [
                "A级客户",
                "稳健型",
                "有理财",
                "有房有车",
                "高消费",
                "爱喝茶"
            ],
            "RecomProducts": [
                "爱奇艺联名信用卡",
                "随薪贷"
            ],
            "customerType": 1,
            "followUpStatus": "待跟进",
            "handeler": "陈志坚",
            "gender": "man",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050829@qq.com",
            "maritalStatus": 1,
            "educationStatus": 2,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 1,
            "personalLoan": 1,
            "credit": 2,
            "timeDeposit": 2,
            "isNew": true,
            "key": "12"
        },
        {
            "id": 13,
            "customerId": "8105183",
            "customerName": "包丽丹",
            "customerAge": 42,
            "customerTel": 17557282525,
            "customerTags": [
                "B级客户",
                "保守型",
                "有信用卡",
                "有房有车",
                "高消费",
                "喜欢运动"
            ],
            "RecomProducts": [
                "汇利丰结构性理财",
                "随薪贷"
            ],
            "customerType": 1,
            "followUpStatus": "待跟进",
            "handeler": "陈志坚",
            "gender": "woman",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050832@qq.com",
            "maritalStatus": 1,
            "educationStatus": 2,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 1,
            "personalLoan": 1,
            "credit": 1,
            "timeDeposit": 2,
            "isNew": true,
            "key": "13"
        },
        {
            "id": 14,
            "customerId": "8106429",
            "customerName": "徐敏",
            "customerAge": 50,
            "customerTel": 15658832227,
            "customerTags": [
                "A级客户",
                "稳健型",
                "有房贷",
                "无房有车",
                "高消费",
                "爱喝茶"
            ],
            "RecomProducts": [
                "网易云音乐联名卡",
                "随薪贷"
            ],
            "customerType": 1,
            "followUpStatus": "待跟进",
            "handeler": "陈志坚",
            "gender": "man",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050832@qq.com",
            "maritalStatus": 1,
            "educationStatus": 1,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 1,
            "personalLoan": 1,
            "credit": 1,
            "timeDeposit": 1,
            "isNew": false,
            "key": "14"
        },
        {
            "id": 15,
            "customerId": "8106922",
            "customerName": "任阿芬",
            "customerAge": 40,
            "customerTel": 13282135559,
            "customerTags": [
                "A级客户",
                "积极型",
                "有信用卡",
                "有房有车",
                "高收入",
                "旅游达人"
            ],
            "RecomProducts": [
                "汇利丰结构性理财",
                "随薪贷"
            ],
            "customerType": 1,
            "followUpStatus": "待跟进",
            "handeler": "陈志坚",
            "gender": "woman",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050832@qq.com",
            "maritalStatus": 1,
            "educationStatus": 1,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 1,
            "personalLoan": 2,
            "credit": 1,
            "timeDeposit": 1,
            "isNew": false,
            "key": "15"
        },
        {
            "id": 16,
            "customerId": "8101464",
            "customerName": "董邦西",
            "customerAge": 45,
            "customerTel": 17682323737,
            "customerTags": [
                "C级客户",
                "稳健型",
                "有理财",
                "有房有车",
                "高消费",
                "爱喝茶"
            ],
            "RecomProducts": [
                "爱奇艺联名信用卡",
                "随薪贷"
            ],
            "customerType": 1,
            "followUpStatus": "跟进",
            "handeler": "陈志坚",
            "gender": "man",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050832@qq.com",
            "maritalStatus": 3,
            "educationStatus": 1,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 1,
            "personalLoan": 2,
            "credit": 1,
            "timeDeposit": 1,
            "isNew": false,
            "key": "16"
        },
        {
            "id": 17,
            "customerId": "8104199",
            "customerName": "鲍式谦",
            "customerAge": 48,
            "customerTel": 13067707337,
            "customerTags": [
                "A级客户",
                "保守型",
                "有信用卡",
                "有房有车",
                "高收入",
                "爱喝茶"
            ],
            "RecomProducts": [
                "网易云音乐联名卡",
                "随薪贷"
            ],
            "customerType": 1,
            "followUpStatus": "跟进",
            "handeler": "陈志坚",
            "gender": "man",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050832@qq.com",
            "maritalStatus": 3,
            "educationStatus": 1,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 2,
            "personalLoan": 2,
            "credit": 1,
            "timeDeposit": 1,
            "isNew": false,
            "key": "17"
        },
        {
            "id": 18,
            "customerId": "8101445",
            "customerName": "吴王相",
            "customerAge": 40,
            "customerTel": 17557282525,
            "customerTags": [
                "A级客户",
                "稳健型",
                "有房贷",
                "有房有车",
                "高消费",
                "喜欢运动"
            ],
            "RecomProducts": [
                "汇利丰结构性理财",
                "随薪贷"
            ],
            "customerType": 1,
            "followUpStatus": "跟进",
            "handeler": "陈志坚",
            "gender": "man",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050832@qq.com",
            "maritalStatus": 3,
            "educationStatus": 2,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 2,
            "personalLoan": 2,
            "credit": 3,
            "timeDeposit": 1,
            "isNew": false,
            "key": "18"
        },
        {
            "id": 19,
            "customerId": "8101445",
            "customerName": "黄道武",
            "customerAge": 46,
            "customerTel": 17606501321,
            "customerTags": [
                "A级客户",
                "稳健型",
                "有理财",
                "有房有车",
                "高消费",
                "爱喝茶"
            ],
            "RecomProducts": [
                "“安心得利”理财",
                "随薪贷"
            ],
            "customerType": 3,
            "followUpStatus": "跟进",
            "handeler": "陈志坚",
            "gender": "man",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050832@qq.com",
            "maritalStatus": 3,
            "educationStatus": 2,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 2,
            "personalLoan": 2,
            "credit": 1,
            "timeDeposit": 1,
            "isNew": false,
            "key": "19"
        },
        {
            "id": 20,
            "customerId": "8101449",
            "customerName": "蔡少博",
            "customerAge": 52,
            "customerTel": 17606505959,
            "customerTags": [
                "A级客户",
                "稳健型",
                "有信用卡",
                "无房无车",
                "高消费",
                "爱喝茶"
            ],
            "RecomProducts": [
                "爱奇艺联名信用卡",
                "个人汽车贷款"
            ],
            "customerType": 3,
            "followUpStatus": "跟进",
            "handeler": "陈志坚",
            "gender": "man",
            "certificatesType": 1,
            "identifyNum": "330301197408123412",
            "email": "404050832@qq.com",
            "maritalStatus": 3,
            "educationStatus": 2,
            "addr": " 浙江省温州市瓯海区瞿溪街道埭头村",
            "company": "中国银行",
            "housingLoan": 2,
            "personalLoan": 2,
            "credit": 1,
            "timeDeposit": 1,
            "isNew": false,
            "key": "20"
        }
    ]
}

export function labelData() {
    return [
        {
            "id": 1,
            "key": 1,
            "labelName": "高风险",
            "labelType": "特征标签",
            "source": "系统",
            "resoult": 426
        },
        {
            "id": 2,
            "key": 2,
            "labelName": "中风险",
            "source": "系统",
            "labelType": "特征标签",
            "resoult": 54
        },
        {
            "id": 3,
            "key": 3,
            "labelName": "稳健型",
            "labelType": "特征标签",
            "source": "系统",
            "resoult": 2445
        },
        {
            "id": 4,
            "key": 4,
            "labelName": "积极型",
            "labelType": "特征标签",
            "source": "系统",
            "resoult": 3452
        },
        {
            "id": 5,
            "key": 5,
            "labelName": "保守型",
            "labelType": "特征标签",
            "source": "系统",
            "resoult": 6436
        },
        {
            "id": 6,
            "key": 6,
            "labelName": "有信用卡",
            "labelType": "特征标签",
            "source": "系统",
            "resoult": 523
        },
        {
            "id": 7,
            "key": 7,
            "labelName": "有理财",
            "labelType": "特征标签",
            "source": "系统",
            "resoult": 656
        },
        {
            "id": 8,
            "key": 8,
            "labelName": "有房贷",
            "labelType": "特征标签",
            "source": "系统",
            "resoult": 332
        },
        {
            "id": 9,
            "key": 9,
            "labelName": "无信用卡",
            "labelType": "特征标签",
            "source": "系统",
            "resoult": 452
        },
        {
            "id": 10,
            "key": 10,
            "labelName": "无贷款",
            "labelType": "特征标签",
            "source": "系统",
            "resoult": 456
        },
        {
            "id": 11,
            "key": 11,
            "labelName": "无理财",
            "labelType": "特征标签",
            "source": "系统",
            "resoult": 8378
        },
        {
            "id": 12,
            "key": 12,
            "labelName": "有车贷",
            "labelType": "特征标签",
            "source": "系统",
            "resoult": 1356
        },
        {
            "id": 13,
            "key": 13,
            "labelName": "无车",
            "labelType": "特征标签",
            "source": "系统",
            "resoult": 3532
        },
        {
            "id": 14,
            "key": 14,
            "labelName": "中等收入",
            "labelType": "特征标签",
            "source": "系统",
            "resoult": 4536
        },
        {
            "id": 15,
            "key": 15,
            "labelName": "高收入",
            "labelType": "特征标签",
            "source": "系统",
            "resoult": 2327
        },
        {
            "id": 16,
            "key": 16,
            "labelName": "A级客户",
            "labelType": "特征标签",
            "source": "系统",
            "resoult": 4654
        },
        {
            "id": 17,
            "key": 17,
            "labelName": "B级客户",
            "labelType": "特征标签",
            "source": "系统",
            "resoult": 4678
        },
        {
            "id": 18,
            "key": 18,
            "labelName": "高消费",
            "labelType": "特征标签",
            "source": "自定义",
            "resoult": 3465
        },
        {
            "id": 19,
            "key": 19,
            "labelName": "旅游达人",
            "labelType": "特征标签",
            "source": "自定义",
            "resoult": 35
        },
        {
            "id": 20,
            "key": 20,
            "labelName": "喜欢运动",
            "labelType": "特征标签",
            "source": "自定义",
            "resoult": 56
        },
        {
            "id": 21,
            "key": 21,
            "labelName": "爱喝茶",
            "labelType": "特征标签",
            "source": "自定义",
            "resoult": 15
        },
        {
            "id": 22,
            "key": 22,
            "labelName": "男",
            "labelType": "基本标签",
            "source": "系统",
            "resoult": 7734
        },
        {
            "id": 23,
            "key": 23,
            "labelName": "女",
            "labelType": "基本标签",
            "source": "系统",
            "resoult": 9734
        }
    ]
}